---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
- name: corporate-ca-certificates
  files:
  - ca-certificates.crt

patchesStrategicMerge:
- statefulset-patch.yaml
- deployment-patch.yaml